### ISSUE TITLE
serializable and serializable_class don't handle nil values the same way

### ISSUE THREAD

**Issue by anthonyjlower** [LaunchPadLab/lp-serializable#16]
@chawes13 / @bhennes2 / @dpikt Tagging you because you're listed as contributors on this repo.

Looking to get context into whether my proposed change is an enhancement or if it would be changing functionality that was included on purpose.

When passing a `nil` value to the `serializable` method it raises `NameError: uninitialized constant NilClassSerializer` as an error because it tries to infer the class name from the `nil` object.

ex:
```
user = User.find(id_that_doesnt_exist)
serializable(user)
=> NameError: uninitialized constant NilClassSerializer
```

When passing a `nil` value to the `serializable_class` method it returns `{:data=>nil}` because it is explicitly told the class.

ex:
```
user = User.find(id_that_doesnt_exist)
serialziable_class(user)
=> {:data=> nil}
```

I think it would make the most sense to include a check where if `serializable` is passed a `nil` value it also responds with {:data=>nil}`. If we think there is value to having `serializable` raise an error then I would add an `ArgumentError` check and return `ArgumentError: Resource cannot be nil`

Wanted to get some level of input or consensus around this before starting the PR.

**Comment by dpikt** [comment]
I think returning `{ :data => nil }` in that case would make sense - I believe it's what `fast_jsonapi` does with `nil` (although you might want to confirm that). I wouldn't consider it a breaking change, since the current behavior is not documented and I doubt projects are relying on it.
